version: 2
updates:
  #Python (Django)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  #Node.js (Vue,...)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  #Dockerfiles
  - package-ecosystem: "docker"
    directories:
      - "/backend"
      - "/frontend"
    schedule:
      interval: "weekly"

  #docker-compose.yml
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  #GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: "weekly"